### ISSUE TITLE
HttpClient created and disposed instead of reused

### ISSUE THREAD

**Issue by hasnik** [gzileni/OverPassAPI#4]
Problematic code location:
File - Overpass/OverPassAPI/OverPass.cs
Method - RunOverPassQuery()
Line - 100

Problem: HttpClient should be reused/pooled, not created and disposed per request.

Explanation: new connection has to be established on every method execution and port exhaustion may happen. [Source](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines#pooled-connections) 

Recommended action: apply to [HttpClient usage guidelines](https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines#recommended-use)

**Comment by gzileni** [comment]
Thanks hasnik, I posted the new version 1.0.2 with the bug fixed.

I hope you will still help me with your contributions.
